### ISSUE TITLE
Coloring in answer-viewing page

### ISSUE THREAD

**Issue by louietyj** [yichenshen/TEACH#5]
Questions are supposedly grey and answers are supposedly green but no one can tell the difference. Can we make the green a little more obviously green? Maybe "lighten-4" instead of "lighten-5".

**Comment by yichenshen** [comment]
I changed them to the current backgrounds after deciding that the original (white) offers too much contrast, and is generally too outstanding for something that should have been "smooth". 

I don't really think it's an issue if it's hard to differentiate them, the colours were superposed to make the background less noticeable, not more, while at the same time giving them a subtle accent.

And lighten-4 is way darker than its name justifies.
![image](https://cloud.githubusercontent.com/assets/3049761/7669826/6a77685e-fcba-11e4-9387-cc8d01e06563.png)

**Comment by louietyj** [comment]
lighten-4 looks good! But it's subjective. You decide.

Bear in mind the header and footer are a solid, dark blue. In context this shade of green already looks quite smooth + you do wanna place some emphasis on it because it's the answer.

**Comment by yichenshen** [comment]
I think the green clashes too much with the borders, will play around a bit with it.
